<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://www.esocial.gov.br/schema/evt/evtAnotJudTSVE/v_S_01_03_00" targetNamespace="http://www.esocial.gov.br/schema/evt/evtAnotJudTSVE/v_S_01_03_00" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
    <xs:include schemaLocation="tipos.xsd" />
    <xs:import namespace="http://www.w3.org/2000/09/xmldsig#" schemaLocation="xmldsig-core-schema.xsd" />
    <xs:element name="eSocial">
        <xs:annotation>
            <xs:documentation>S-8300 - Anotação Judicial do Trabalhador Sem Vínculo de Emprego/Estatutário</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element name="evtAnotJudTSVE">
                    <xs:annotation>
                        <xs:documentation>Evento Anotação Judicial do TSVE.</xs:documentation>
                        <xs:documentation>DESCRICAO_COMPLETA:Evento Anotação Judicial do Trabalhador Sem Vínculo de Emprego/Estatutário (TSVE).</xs:documentation>
                        <xs:documentation>CHAVE_GRUPO: {Id}</xs:documentation>
                        <xs:documentation>REGRA:REGRA_BLOQUEIA_USO_CPF_EMPREGADOR</xs:documentation>
                        <xs:documentation>REGRA:REGRA_COMPATIBILIDADE_CATEGORIA_CLASSTRIB</xs:documentation>
                        <xs:documentation>REGRA:REGRA_ENVIO_PROC_FECHAMENTO</xs:documentation>
                        <xs:documentation>REGRA:REGRA_EVENTOS_EXTEMP</xs:documentation>
                        <xs:documentation>REGRA:REGRA_EXISTE_INFO_EMPREGADOR</xs:documentation>
                        <xs:documentation>REGRA:REGRA_RETIFICA_MESMO_VINCULO</xs:documentation>
                        <xs:documentation>REGRA:REGRA_VALIDA_MATRICULA</xs:documentation>
                        <xs:documentation>REGRA:REGRA_VALIDA_TRABALHADOR_BASE_CPF</xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ideEvento" type="T_ideEvento_trab_jud" />
                            <xs:element name="ideEmpregador" type="T_ideEmpregador" />
                            <xs:element name="infoProcesso">
                                <xs:annotation>
                                    <xs:documentation>Informações do processo judicial.</xs:documentation>
                                </xs:annotation>
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nrProcTrab" type="TS_nrProcJud">
                                            <xs:annotation>
                                                <xs:documentation>Número que identifica o processo judicial onde a anotação do contrato foi determinada.</xs:documentation>
                                                <xs:documentation>Validação: Deve ser um processo judicial válido, com 20 (vinte) algarismos.</xs:documentation>
                                            </xs:annotation>
                                        </xs:element>
                                        <xs:element name="dtSent" type="xs:date">
                                            <xs:annotation>
                                                <xs:documentation>Informar a data da decisão judicial.</xs:documentation>
                                            </xs:annotation>
                                        </xs:element>
                                        <xs:element name="ufVara" type="TS_uf">
                                            <xs:annotation>
                                                <xs:documentation>Preencher com a sigla da Unidade da Federação onde está localizada a Vara em que o processo tramitou.</xs:documentation>
                                            </xs:annotation>
                                        </xs:element>
                                        <xs:element name="codMunic" type="TS_codMunic" />
                                        <xs:element name="idVara">
                                            <xs:simpleType>
                                                <xs:annotation>
                                                    <xs:documentation>Código de identificação da Vara em que o processo tramitou.</xs:documentation>
                                                </xs:annotation>
                                                <xs:restriction base="xs:integer">
                                                    <xs:pattern value="\d{1,4}" />
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="infoAnotJud">
                                <xs:annotation>
                                    <xs:documentation>Informações da anotação judicial do TSVE.</xs:documentation>
                                    <xs:documentation>CHAVE_GRUPO: {cpfTrab*}, {matricula*}</xs:documentation>
                                </xs:annotation>
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="cpfTrab" type="TS_cpfTrab" />
                                        <xs:element name="nmTrab" type="TS_nmTrab" />
                                        <xs:element name="dtNascto" type="xs:date">
                                            <xs:annotation>
                                                <xs:documentation>Preencher com a data de nascimento.</xs:documentation>
                                            </xs:annotation>
                                        </xs:element>
                                        <xs:element name="nmSoc" minOccurs="0" type="TS_nmSoc" />
                                        <xs:element name="dtInicio" type="TS_dt1890">
                                            <xs:annotation>
                                                <xs:documentation>Data de início, que pode ser:</xs:documentation>
                                                <xs:documentation>a) Para o cooperado, a data de ingresso na cooperativa;</xs:documentation>
                                                <xs:documentation>b) Para o diretor não empregado, a data de posse no cargo;</xs:documentation>
                                                <xs:documentation>c) Para o estagiário, a data de início do estágio;</xs:documentation>
                                                <xs:documentation>d) Para o trabalhador avulso, a data de ingresso no Órgão Gestor de Mão de Obra - OGMO ou no sindicato;</xs:documentation>
                                                <xs:documentation>e) Para os demais trabalhadores, a data de início das atividades.</xs:documentation>
                                            </xs:annotation>
                                        </xs:element>
                                        <xs:element name="matricula" type="TS_codigo_esocial">
                                            <xs:annotation>
                                                <xs:documentation>Matrícula atribuída ao trabalhador.</xs:documentation>
                                                <xs:documentation>Validação: O valor informado deve conter a expressão 'eSocial-JUD-' nas 12 (doze) primeiras posições.</xs:documentation>
                                                <xs:documentation>REGRA:REGRA_CARACTERE_ESPECIAL</xs:documentation>
                                            </xs:annotation>
                                        </xs:element>
                                        <xs:element name="codCateg" type="TS_codCateg">
                                            <xs:annotation>
                                                <xs:documentation>Preencher com o código da categoria do trabalhador.</xs:documentation>
                                                <xs:documentation>Validação: Deve ser um código de categoria referente a "Avulso", "Contribuinte Individual" ou "Bolsista" ([2XX, 7XX, 9XX]).</xs:documentation>
                                            </xs:annotation>
                                        </xs:element>
                                        <xs:element name="natAtividade" minOccurs="0" type="TS_natAtividade">
                                            <xs:annotation>
                                                <xs:documentation>Natureza da atividade.</xs:documentation>
                                                <xs:documentation>Validação: Preenchimento obrigatório se {codCateg}(./codCateg) for relativo a "Avulso" ou igual a [731, 734, 738]. Não deve ser preenchido se {codCateg}(./codCateg) = [721, 722, 771, 901].</xs:documentation>
                                            </xs:annotation>
                                        </xs:element>
                                        <xs:element name="tpInscTrab" minOccurs="0" type="TS_tpInsc_1_3_4">
                                            <xs:annotation>
                                                <xs:documentation>Preencher com o código correspondente ao tipo de inscrição do estabelecimento relativo ao local de trabalho.</xs:documentation>
                                                <xs:documentation>Validação: Não preencher se {codCateg}(./codCateg) = [701, 711, 712, 741, 751, 781, 903, 904, 905].</xs:documentation>
                                            </xs:annotation>
                                        </xs:element>
                                        <xs:element name="localTrabalho" minOccurs="0" type="TS_nrInsc_12_14">
                                            <xs:annotation>
                                                <xs:documentation>Informar o número de inscrição do estabelecimento relativo ao local de trabalho.</xs:documentation>
                                                <xs:documentation>Validação: Preenchimento obrigatório e exclusivo se {tpInscTrab}(./tpInscTrab) for informado.</xs:documentation>
                                                <xs:documentation>Deve ser um identificador válido, constante das bases da RFB, conforme indicado em {tpInscTrab}(./tpInscTrab).</xs:documentation>
                                            </xs:annotation>
                                        </xs:element>
                                        <xs:element name="cargo" minOccurs="0" maxOccurs="99">
                                            <xs:annotation>
                                                <xs:documentation>Informações do cargo.</xs:documentation>
                                                <xs:documentation>CHAVE_GRUPO: {dtCargo}</xs:documentation>
                                                <xs:documentation>CONDICAO_GRUPO: OC (se {codCateg}(../codCateg) = [901, 903, 904, 906]); O (nos demais casos)</xs:documentation>
                                            </xs:annotation>
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="dtCargo" type="xs:date">
                                                        <xs:annotation>
                                                            <xs:documentation>Data a partir da qual as informações do cargo estão vigentes.</xs:documentation>
                                                            <xs:documentation>Validação: Deve ser igual ou posterior a {dtInicio}(../dtInicio) e igual ou anterior a {dtTerm}(8300_infoAnotJud_termino_dtTerm), se informado.</xs:documentation>
                                                        </xs:annotation>
                                                    </xs:element>
                                                    <xs:element name="CBOCargo" type="TS_cbo">
                                                        <xs:annotation>
                                                            <xs:documentation>Informar a Classificação Brasileira de Ocupações - CBO relativa ao cargo.</xs:documentation>
                                                            <xs:documentation>Validação: Deve ser um código válido e existente na tabela de CBO, com 6 (seis) posições.</xs:documentation>
                                                        </xs:annotation>
                                                    </xs:element>
                                                    <xs:element name="nmCargo" type="TS_texto_100">
                                                        <xs:annotation>
                                                            <xs:documentation>Informar o nome do cargo.</xs:documentation>
                                                        </xs:annotation>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="remuneracao" minOccurs="0" maxOccurs="99">
                                            <xs:annotation>
                                                <xs:documentation>Informações da remuneração e periodicidade de pagamento.</xs:documentation>
                                                <xs:documentation>CHAVE_GRUPO: {dtRemun}</xs:documentation>
                                                <xs:documentation>CONDICAO_GRUPO: O (se {codCateg}(../codCateg) = [721, 722, 771, 906]); OC (nos demais casos)</xs:documentation>
                                            </xs:annotation>
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="dtRemun" type="xs:date">
                                                        <xs:annotation>
                                                            <xs:documentation>Data a partir da qual as informações de remuneração e periodicidade de pagamento estão vigentes.</xs:documentation>
                                                            <xs:documentation>Validação: Deve ser igual ou posterior a {dtInicio}(../dtInicio) e igual ou anterior a {dtTerm}(8300_infoAnotJud_termino_dtTerm), se informado.</xs:documentation>
                                                        </xs:annotation>
                                                    </xs:element>
                                                    <xs:element name="vrSalFx" type="TS_vrSalFx">
                                                        <xs:annotation>
                                                            <xs:documentation>Salário base do trabalhador, correspondente à parte fixa da remuneração em {dtRemun}(./dtRemun).</xs:documentation>
                                                            <xs:documentation>Validação: Se {undSalFixo}(./undSalFixo) for igual a [7], preencher com 0 (zero).</xs:documentation>
                                                        </xs:annotation>
                                                    </xs:element>
                                                    <xs:element name="undSalFixo" type="TS_undSalFixo" />
                                                    <xs:element name="dscSalVar" minOccurs="0" type="TS_texto_999">
                                                        <xs:annotation>
                                                            <xs:documentation>Descrição do salário por tarefa ou variável e como este é calculado. Ex.: Comissões pagas no percentual de 10% sobre as vendas.</xs:documentation>
                                                            <xs:documentation>Validação: Preenchimento obrigatório se {undSalFixo}(./undSalFixo) for igual a [6, 7].</xs:documentation>
                                                        </xs:annotation>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="incorporacao" minOccurs="0" maxOccurs="9">
                                            <xs:annotation>
                                                <xs:documentation>Informação do(s) contrato(s) já declarado(s) no eSocial e incorporado(s) ao contrato reconhecido judicialmente.</xs:documentation>
                                                <xs:documentation>CHAVE_GRUPO: {tpInsc}, {nrInsc}, {matIncorp}</xs:documentation>
                                                <xs:documentation>CONDICAO_GRUPO: OC</xs:documentation>
                                            </xs:annotation>
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="tpInsc" type="TS_tpInsc_1_2">
                                                        <xs:annotation>
                                                            <xs:documentation>Preencher com o código correspondente ao tipo de inscrição, conforme Tabela 05.</xs:documentation>
                                                        </xs:annotation>
                                                    </xs:element>
                                                    <xs:element name="nrInsc" type="TS_nrInsc_8_11_14">
                                                        <xs:annotation>
                                                            <xs:documentation>Informar o número de inscrição do empregador no qual consta a matrícula incorporada ou sucedida, de acordo com o tipo de inscrição indicado no campo {incorporacao/tpInsc}(./tpInsc).</xs:documentation>
                                                        </xs:annotation>
                                                    </xs:element>
                                                    <xs:element name="matIncorp" type="TS_matricula">
                                                        <xs:annotation>
                                                            <xs:documentation>Informar a matrícula incorporada (matrícula cujo contrato passou a integrar o vínculo reconhecido judicialmente).</xs:documentation>
                                                            <xs:documentation>Validação: Deve corresponder a uma matrícula informada pelo empregador no evento S-2190 (exclusivamente cujos códigos de categoria sejam iguais a [2XX, 721, 722, 723, 731, 734, 738, 761, 771, 901, 902]) ou S-2300, pertencente ao trabalhador preenchido em {cpfTrab}(../cpfTrab), no empregador informado em {incorporacao/nrInsc}(./nrInsc).</xs:documentation>
                                                        </xs:annotation>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="afastamento" minOccurs="0">
                                            <xs:annotation>
                                                <xs:documentation>Informações de afastamento do trabalhador.</xs:documentation>
                                                <xs:documentation>CONDICAO_GRUPO: N (se grupo {termino}(../termino) estiver preenchido); OC (nos demais casos)</xs:documentation>
                                            </xs:annotation>
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="dtIniAfast" type="xs:date">
                                                        <xs:annotation>
                                                            <xs:documentation>Data de início do afastamento.</xs:documentation>
                                                            <xs:documentation>Validação: Deve ser igual ou posterior a {dtInicio}(../dtInicio).</xs:documentation>
                                                            <xs:documentation>Não pode ser posterior à data atual.</xs:documentation>
                                                        </xs:annotation>
                                                    </xs:element>
                                                    <xs:element name="codMotAfast" type="TS_codMotAfast">
                                                        <xs:annotation>
                                                            <xs:documentation>Preencher com o código do motivo de afastamento temporário.</xs:documentation>
                                                            <xs:documentation>Validação: Deve ser um código válido e existente na Tabela 18, bem como compatível com o código de categoria do trabalhador, conforme Tabela 18.</xs:documentation>
                                                            <xs:documentation>Somente podem ser informados os códigos [01, 03, 11, 17, 18, 19, 20, 24, 29, 35, 43, 46, 47, 48, 49, 50, 51, 52].</xs:documentation>
                                                        </xs:annotation>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="termino" minOccurs="0">
                                            <xs:annotation>
                                                <xs:documentation>Informações do término do TSVE.</xs:documentation>
                                                <xs:documentation>CONDICAO_GRUPO: N (se grupo {afastamento}(../afastamento) estiver preenchido); OC (nos demais casos)</xs:documentation>
                                            </xs:annotation>
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="mtvDesligTSV" minOccurs="0">
                                                        <xs:simpleType>
                                                            <xs:annotation>
                                                                <xs:documentation>Motivo do término.</xs:documentation>
                                                                <xs:documentation>Validação: Informação obrigatória e exclusiva se {codCateg}(../codCateg) = [721].</xs:documentation>
                                                            </xs:annotation>
                                                            <xs:restriction base="xs:string">
                                                                <xs:enumeration value="01">
                                                                    <xs:annotation>
                                                                        <xs:documentation>Exoneração do diretor não empregado sem justa causa, por deliberação da assembleia, dos sócios cotistas ou da autoridade competente</xs:documentation>
                                                                    </xs:annotation>
                                                                </xs:enumeration>
                                                                <xs:enumeration value="02">
                                                                    <xs:annotation>
                                                                        <xs:documentation>Término de mandato do diretor não empregado que não tenha sido reconduzido ao cargo</xs:documentation>
                                                                    </xs:annotation>
                                                                </xs:enumeration>
                                                                <xs:enumeration value="03">
                                                                    <xs:annotation>
                                                                        <xs:documentation>Exoneração a pedido de diretor não empregado</xs:documentation>
                                                                    </xs:annotation>
                                                                </xs:enumeration>
                                                                <xs:enumeration value="04">
                                                                    <xs:annotation>
                                                                        <xs:documentation>Exoneração do diretor não empregado por culpa recíproca ou força maior</xs:documentation>
                                                                    </xs:annotation>
                                                                </xs:enumeration>
                                                                <xs:enumeration value="05">
                                                                    <xs:annotation>
                                                                        <xs:documentation>Morte do diretor não empregado</xs:documentation>
                                                                    </xs:annotation>
                                                                </xs:enumeration>
                                                                <xs:enumeration value="06">
                                                                    <xs:annotation>
                                                                        <xs:documentation>Exoneração do diretor não empregado por falência, encerramento ou supressão de parte da empresa</xs:documentation>
                                                                    </xs:annotation>
                                                                </xs:enumeration>
                                                                <xs:enumeration value="99">
                                                                    <xs:annotation>
                                                                        <xs:documentation>Outros</xs:documentation>
                                                                    </xs:annotation>
                                                                </xs:enumeration>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element name="dtTerm" type="xs:date">
                                                        <xs:annotation>
                                                            <xs:documentation>Preencher com a data do término.</xs:documentation>
                                                            <xs:documentation>Validação: Deve ser igual ou posterior a {dtInicio}(../dtInicio). Não pode ser posterior à data atual.</xs:documentation>
                                                            <xs:documentation>Se {mtvDesligTSV}(./mtvDesligTSV) = [05]:</xs:documentation>
                                                            <xs:documentation>a) Caso a situação no cadastro do CPF na RFB seja diferente de "Titular Falecido", retornar erro até o 7º (sétimo) dia de {dtTerm}(./dtTerm) e retornar alerta a partir do 8º (oitavo) dia de {dtTerm}(./dtTerm);</xs:documentation>
                                                            <xs:documentation>b) Caso a situação no cadastro do CPF na RFB seja igual a "Titular Falecido", {dtTerm}(./dtTerm) deve ser igual à data de óbito no cadastro do CPF da RFB (se não for possível obter a data do óbito, o ano de {dtTerm}(./dtTerm) deve ser igual ao ano do óbito; se não for possível obter a data e o ano do óbito, o evento deve ser recebido mediante alerta).</xs:documentation>
                                                        </xs:annotation>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="Id" use="required" type="TS_Id" />
                    </xs:complexType>
                </xs:element>
                <xs:element ref="ds:Signature" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>